<a href="https://colab.research.google.com/github/Aksingh9717/Machine-Learning-data-science/blob/main/Column_Transform.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [3]:
df = pd.read_csv('/content/covid_toy.csv')

In [4]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [5]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train,y_test = train_test_split(df.drop(columns=['has_covid']),
                                                   df['has_covid'],test_size=0.2)

In [9]:
X_train

    age  gender  fever   cough       city
4    65  Female  101.0    Mild     Mumbai
22   71  Female   98.0  Strong    Kolkata
11   65  Female   98.0    Mild     Mumbai
80   14  Female   99.0    Mild     Mumbai
20   12    Male   98.0  Strong  Bangalore
..  ...     ...    ...     ...        ...
92   82  Female  102.0  Strong    Kolkata
41   82    Male    NaN    Mild    Kolkata
34   74    Male  102.0    Mild     Mumbai
42   27    Male  100.0    Mild      Delhi
78   11    Male  100.0    Mild  Bangalore

[80 rows x 5 columns]

In [10]:
y_train

4      No
22    Yes
11    Yes
80    Yes
20     No
     ...
92     No
41    Yes
34    Yes
42    Yes
78    Yes
Name: has_covid, Length: 80, dtype: object

In [11]:
from sklearn.compose import ColumnTransformer

In [16]:
transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OneHotEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(sparse_output=False,drop='first'),['gender','city'])
],remainder='passthrough')

In [17]:
transformer.fit_transform(X_train)

array([[101.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   1.        ,  65.        ],
       [ 98.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   1.        ,   0.        ,  71.        ],
       [ 98.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   1.        ,  65.        ],
       [ 99.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   1.        ,  14.        ],
       [ 98.        ,   0.        ,   1.        ,   1.        ,
          0.        ,   0.        ,   0.        ,  12.        ],
       [103.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   1.        ,   0.        ,  60.        ],
       [104.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   0.        ,  56.        ],
       [ 99.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   1.        ,  60.        ],
       [102.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   0.        ,  82.        ],
       [100.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   0.        ,  19.        ],
       [102.        ,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   0.        ,  33.        ],
       [104.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   0.        ,  51.        ],
       [103.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   1.        ,   0.        ,  69.        ],
       [ 98.        ,   0.        ,   1.        ,   1.        ,
          0.        ,   0.        ,   1.        ,  23.        ],
       [100.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   1.        ,   0.        ,  11.        ],
       [101.        ,   1.        ,   0.        ,   1.        ,
          1.        ,   0.        ,   0.        ,  15.        ],
       [100.89041096,   0.        ,   1.        ,   1.        ,
          0.        ,   1.        ,   0.        ,  71.        ],
       [101.        ,   0.        ,   1.        ,   1.        ,
          0.        ,   0.        ,   0.        ,  14.        ],
       [100.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   0.        ,  10.        ],
       [104.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   1.        ,   0.        ,  51.        ],
       [100.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   1.        ,   0.        ,  55.        ],
       [ 98.        ,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   0.        ,  40.        ],
       [100.89041096,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   1.        ,  34.        ],
       [102.        ,   0.        ,   1.        ,   1.        ,
          1.        ,   0.        ,   0.        ,  20.        ],
       [103.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ,  16.        ],
       [101.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   1.        ,   0.        ,   8.        ],
       [ 99.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   1.        ,   0.        ,  25.        ],
       [104.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ,  18.        ],
       [104.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   1.        ,   0.        ,  54.        ],
       [ 99.        ,   1.        ,   0.        ,   1.        ,
          1.        ,   0.        ,   0.        ,  65.        ],
       [ 98.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   0.        ,  73.        ],
       [ 98.        ,   1.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   0.        ,  80.        ],
       [102.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ,  69.        ],
       [100.89041096,   0.        ,   1.        ,   1.        ,
          0.        ,   1.        ,   0.        ,  79.        ],
       [ 98.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   1.        ,   0.        ,  24.        ],
       [103.        ,   0.        ,   1.        ,   1.        ,
          0.        ,   0.        ,   0.        ,  46.        ],
       [104.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   1.        ,   0.        ,   6.        ],
       [104.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   0.        ,  25.        ],
       [ 99.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   0.        ,  49.        ],
       [101.        ,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   0.        ,  68.        ],
       [ 98.        ,   1.        ,   0.        ,   1.        ,
          1.        ,   0.        ,   0.        ,  83.        ],
       [101.        ,   1.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   0.        ,  64.        ],
       [102.        ,   1.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   0.        ,  49.        ],
       [101.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   1.        ,   0.        ,  83.        ],
       [ 99.        ,   0.        ,   1.        ,   1.        ,
          0.        ,   0.        ,   0.        ,  66.        ],
       [ 98.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   1.        ,   0.        ,  10.        ],
       [103.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   1.        ,   0.        ,  48.        ],
       [102.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   0.        ,  24.        ],
       [ 98.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ,  64.        ],
       [101.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   1.        ,   0.        ,  51.        ],
       [100.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   0.        ,  80.        ],
       [103.        ,   0.        ,   1.        ,   1.        ,
          0.        ,   1.        ,   0.        ,  70.        ],
       [102.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   1.        ,   0.        ,   5.        ],
       [101.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   1.        ,  81.        ],
       [100.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   0.        ,  47.        ],
       [100.89041096,   1.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   0.        ,  75.        ],
       [100.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   1.        ,   0.        ,  13.        ],
       [104.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   1.        ,  42.        ],
       [104.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ,  12.        ],
       [101.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ,  20.        ],
       [100.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   1.        ,   0.        ,  27.        ],
       [101.        ,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   0.        ,  34.        ],
       [101.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ,  38.        ],
       [103.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   1.        ,   0.        ,  83.        ],
       [100.89041096,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ,  84.        ],
       [100.89041096,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   1.        ,  23.        ],
       [101.        ,   1.        ,   0.        ,   1.        ,
          1.        ,   0.        ,   0.        ,  19.        ],
       [ 99.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   0.        ,  72.        ],
       [104.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   1.        ,  44.        ],
       [103.        ,   1.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   0.        ,  73.        ],
       [100.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   1.        ,   0.        ,   5.        ],
       [ 98.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   1.        ,   0.        ,  26.        ],
       [ 99.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   0.        ,  65.        ],
       [ 99.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ,  22.        ],
       [103.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   1.        ,   0.        ,  50.        ],
       [102.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   1.        ,   0.        ,  82.        ],
       [100.89041096,   1.        ,   0.        ,   1.        ,
          0.        ,   1.        ,   0.        ,  82.        ],
       [102.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   1.        ,  74.        ],
       [100.        ,   1.        ,   0.        ,   1.        ,
          1.        ,   0.        ,   0.        ,  27.        ],
       [100.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   0.        ,  11.        ]])

In [19]:
transformer.fit_transform(X_train).shape

(80, 8)

In [21]:
transformer.transform(X_test).shape

(20, 8)